### ISSUE TITLE
打包过一次后，再次打包会报错

### ISSUE THREAD

**Issue by vip7kk** [Moosphan/app-code-obfuscation#6]
codeGuard {
    //开启插件
    enable = true
    maxMethodCount = 26
    maxFieldCount = 26
    maxCodeLineCount = 26
    generatedMethodCount = 26
    genClassCount = 26
}
多次打包有时候会报错，目前第一次打包即使不开混淆打包出来运行会闪退，我反编译看是报错提示找不到的包名和类丢失了，我下载仓库demo打包运行也一样，报错日志：java.lang.NoClassDefFoundError: Failed resolution of: Lcn/xcolyu/kceurni/l/d/w/h/Xl;
                                                                                                    	at cn.xcolyu.kceurni.bc.onCreate(Unknown Source:4)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1236)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6971)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:259)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2127)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:230)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7901)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.xcolyu.kceurni.l.d.w.h.Xl" on path: DexPathList[[zip file "/data/app/cn.xcolyu.kceurni-uXo3xuB3gg8sIv4E-cEYhw==/base.apk"],nativeLibraryDirectories=[/data/app/cn.xcolyu.kceurni-uXo3xuB3gg8sIv4E-cEYhw==/lib/arm64, /system/lib64, /system/product/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at cn.xcolyu.kceurni.bc.onCreate(Unknown Source:4) 
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1236) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6971) 
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:259) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2127) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:230) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7901) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
2024-01-09 13:56:44.057 32630-32630 AndroidRuntime          cn.xcolyu.kceurni                    E  FATAL EXCEPTION: main
                                                                                                    Process: cn.xcolyu.kceurni, PID: 32630
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcn/xcolyu/kceurni/z/c/t/Zd;
                                                                                                    	at cn.xcolyu.kceurni.bc.onCreate(Unknown Source:5)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1236)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6971)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:259)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2127)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:230)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7901)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.xcolyu.kceurni.z.c.t.Zd" on path: DexPathList[[zip file "/data/app/cn.xcolyu.kceurni-wDnYiGPgRyC6j945qojAkA==/base.apk"],nativeLibraryDirectories=[/data/app/cn.xcolyu.kceurni-wDnYiGPgRyC6j945qojAkA==/lib/arm64, /system/lib64, /system/product/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by indieexplore** [comment]
@vip7kk 好的，我看下

**Comment by indieexplore** [comment]
@vip7kk 找到原因了，晚会发个版本

**Comment by indieexplore** [comment]
> > @vip7kk 好的，我看下，是 release 包有问题吗
> 
> 我找到问题了，我设置processingPackages后打包就不会闪退，但是重复打包编译失败的问题还是会出现，而且打包还会在我源码文件里面生成垃圾代码，然后生成的垃圾代码调用的方法参数全是0，最好是随机生成数字，如果打包报错失败了，我需要把源码里生成的垃圾代码删掉再clean后重新打包才行

这个问题我后面看看怎么优化下🤔

**Comment by Moosphan** [comment]
> > @vip7kk 好的，我看下，是 release 包有问题吗
> 
> 我找到问题了，我设置processingPackages后打包就不会闪退，但是重复打包编译失败的问题还是会出现，而且打包还会在我源码文件里面生成垃圾代码，然后生成的垃圾代码调用的方法参数全是0，最好是随机生成数字，如果打包报错失败了，我需要把源码里生成的垃圾代码删掉再clean后重新打包才行

用 `0.1.1-beta` 版本试下，修复了闪退和同名类覆盖问题

**Comment by indieexplore** [comment]
@vip7kk 还是同样的日志吗，我这边用项目验证过了，没出现问题，之前是因为接口中插入了变量导致的，clean下再试试看

**Comment by indieexplore** [comment]
> > @vip7kk 还是同样的日志吗，我这边用项目验证过了，没出现问题，之前是因为接口中插入了变量导致的，clean下再试试看
> 
> 我试了好多次，有的时候正常，有的时候就闪退

可以在debug下打个包，logcat 切换为 `No filters` 模式，然后关注下 `dex2oat` 和 `ArtService` 两个 TAG，看下有无相关信息

**Comment by indieexplore** [comment]
> 我发现一个诡异的问题，出现运行闪退的情况，clean后关掉当前项目，再重新打开运行就正常了，我试了3次都是这样，然后开了混淆后，发现生成垃圾代码效果很差了

开混淆后效果很差是什么意思

**Comment by indieexplore** [comment]
> > > 我发现一个诡异的问题，出现运行闪退的情况，clean后关掉当前项目，再重新打开运行就正常了，我试了3次都是这样，然后开了混淆后，发现生成垃圾代码效果很差了
> > 
> > 
> > 开混淆后效果很差是什么意思
> 
> ![image](https://private-user-images.githubusercontent.com/13134448/295502662-902dffd4-6fb2-4d06-a7a4-d8a14c12098c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzYzMzYsIm5iZiI6MTcwNDg3NjAzNiwicGF0aCI6Ii8xMzEzNDQ0OC8yOTU1MDI2NjItOTAyZGZmZDQtNmZiMi00ZDA2LWE3YTQtZDhhMTRjMTIwOThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA4NDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MjFkOTI5YTg2NDE4OGIzMjBmZDgzN2IwZjMyNWFhY2IyYTJlMDRjNDVlNjgyNDNjNzc4NWJiOWIwOTBkN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zb2Bew6LBjdDONZTEEoznp2s9AQck2_yNYeZu18m8FI) 第一张图是开了混淆后的效果 ![image](https://private-user-images.githubusercontent.com/13134448/295502969-dd56768c-5804-4c11-861c-9f81e9132969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzYzMzYsIm5iZiI6MTcwNDg3NjAzNiwicGF0aCI6Ii8xMzEzNDQ0OC8yOTU1MDI5NjktZGQ1Njc2OGMtNTgwNC00YzExLTg2MWMtOWY4MWU5MTMyOTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA4NDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZTVkMzE3YWQwMWVlNTQ1NDM0MmNlZjZjZjc0Yzk5ZDNjMmFhNzY0NDlhYmM3OWI0Y2NmNDkyZTgzNzMzN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AuaVp0uPpwVEz6I6uyb0_0krd5yYFTZEDlG0BYjrckc) 第二张是没开混淆的效果

是方法内的代码混淆被优化掉了是吗🤔

**Comment by indieexplore** [comment]
> > > > > 我发现一个诡异的问题，出现运行闪退的情况，clean后关掉当前项目，再重新打开运行就正常了，我试了3次都是这样，然后开了混淆后，发现生成垃圾代码效果很差了
> > > > 
> > > > 
> > > > 开混淆后效果很差是什么意思
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/13134448/295502662-902dffd4-6fb2-4d06-a7a4-d8a14c12098c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzYzMzYsIm5iZiI6MTcwNDg3NjAzNiwicGF0aCI6Ii8xMzEzNDQ0OC8yOTU1MDI2NjItOTAyZGZmZDQtNmZiMi00ZDA2LWE3YTQtZDhhMTRjMTIwOThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA4NDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MjFkOTI5YTg2NDE4OGIzMjBmZDgzN2IwZjMyNWFhY2IyYTJlMDRjNDVlNjgyNDNjNzc4NWJiOWIwOTBkN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zb2Bew6LBjdDONZTEEoznp2s9AQck2_yNYeZu18m8FI) 第一张图是开了混淆后的效果 ![image](https://private-user-images.githubusercontent.com/13134448/295502969-dd56768c-5804-4c11-861c-9f81e9132969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzYzMzYsIm5iZiI6MTcwNDg3NjAzNiwicGF0aCI6Ii8xMzEzNDQ0OC8yOTU1MDI5NjktZGQ1Njc2OGMtNTgwNC00YzExLTg2MWMtOWY4MWU5MTMyOTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA4NDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZTVkMzE3YWQwMWVlNTQ1NDM0MmNlZjZjZjc0Yzk5ZDNjMmFhNzY0NDlhYmM3OWI0Y2NmNDkyZTgzNzMzN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AuaVp0uPpwVEz6I6uyb0_0krd5yYFTZEDlG0BYjrckc) 第二张是没开混淆的效果
> > 
> > 
> > 是方法内的代码混淆被优化掉了是吗🤔
> 
> 看起来好像是的，全没了...

是不是开了什么混淆配置，优化代码如内联之类的

**Comment by indieexplore** [comment]
> > > > > > > 我发现一个诡异的问题，出现运行闪退的情况，clean后关掉当前项目，再重新打开运行就正常了，我试了3次都是这样，然后开了混淆后，发现生成垃圾代码效果很差了
> > > > > > 
> > > > > > 
> > > > > > 开混淆后效果很差是什么意思
> > > > > 
> > > > > 
> > > > > ![image](https://private-user-images.githubusercontent.com/13134448/295502662-902dffd4-6fb2-4d06-a7a4-d8a14c12098c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzYzMzYsIm5iZiI6MTcwNDg3NjAzNiwicGF0aCI6Ii8xMzEzNDQ0OC8yOTU1MDI2NjItOTAyZGZmZDQtNmZiMi00ZDA2LWE3YTQtZDhhMTRjMTIwOThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA4NDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MjFkOTI5YTg2NDE4OGIzMjBmZDgzN2IwZjMyNWFhY2IyYTJlMDRjNDVlNjgyNDNjNzc4NWJiOWIwOTBkN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zb2Bew6LBjdDONZTEEoznp2s9AQck2_yNYeZu18m8FI) 第一张图是开了混淆后的效果 ![image](https://private-user-images.githubusercontent.com/13134448/295502969-dd56768c-5804-4c11-861c-9f81e9132969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzYzMzYsIm5iZiI6MTcwNDg3NjAzNiwicGF0aCI6Ii8xMzEzNDQ0OC8yOTU1MDI5NjktZGQ1Njc2OGMtNTgwNC00YzExLTg2MWMtOWY4MWU5MTMyOTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA4NDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZTVkMzE3YWQwMWVlNTQ1NDM0MmNlZjZjZjc0Yzk5ZDNjMmFhNzY0NDlhYmM3OWI0Y2NmNDkyZTgzNzMzN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AuaVp0uPpwVEz6I6uyb0_0krd5yYFTZEDlG0BYjrckc) 第二张是没开混淆的效果
> > > > 
> > > > 
> > > > 是方法内的代码混淆被优化掉了是吗🤔
> > > 
> > > 
> > > 看起来好像是的，全没了...
> > 
> > 
> > 是不是开了什么混淆配置，优化代码如内联之类的
> 
> 我去掉了所有混淆配置，只留了第三方库keep混淆规则，打出来的包垃圾代码没被优化了，但是安装运行报错：java.lang.NoClassDefFoundError: Failed resolution of: Lcn/xcolyu/kceurni/i/d/u/Dn; at cn.xcolyu.kceurni.bc.onCreate(Unknown Source:4) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1285) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7257) at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2292) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:240) at android.os.Looper.loop(Looper.java:351) at android.app.ActivityThread.main(ActivityThread.java:8423) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) Caused by: java.lang.ClassNotFoundException: cn.xcolyu.kceurni.i.d.u.Dn

@vip7kk 如果可以的话，可以提供下Android proguard混淆配置（keep规则无需提供）以及第三方插件混淆配置，以及去敏后的全量log，我来集中看下

**Comment by indieexplore** [comment]
@vip7kk 把 `-allowaccessmodification`  注释掉看看，另外，你处理的包中存在注解类吗

**Comment by indieexplore** [comment]
@vip7kk 晚上打个版本，找到问题了

**Comment by Moosphan** [comment]
@vip7kk 试试 `0.1.2-beta` 版本

**Comment by indieexplore** [comment]
@vip7kk 目前仅支持单个模块集成，后面改一下支持jar

**Comment by Moosphan** [comment]
@vip7kk 更新到 `0.1.3-beta`，如果构建失败会自动清除生成的随机类

**Comment by Moosphan** [comment]
如有问题可以另提 issue，本问题关闭
